#!/bin/bash
opt="$1"
if [ -z "$opt" ]; then
    echo "1. Print all image types (N: current, P: possible)"
    echo "2. Current settings"
    echo "3. All the available settings"
    read -p "Option: " opt
fi
python2 $(dirname "$0")/../py/get-filetype.py "$opt"
