#!/bin/bash
duration="$1"
if [ -z "$duration" ]; then
    read -p "Duration in seconds: " duration
fi
this="$(realpath $(dirname "$0"))"
folder="$1"
if [ -z "$folder" ]; then
    read -e -p "Folder: " folder
fi
cd "$folder"
echo "Capturing..."
gphoto2 --set-config movie=1 "--wait-event=${duration}s" --set-config movie=0 --quiet
echo "Downloading..."
sleep 1
$this/get-last-photo .
