#!/bin/bash
opt=$1
if [ -z $opt ]; then
    cd bin
    read -e -p "Please specify the movie lenght in seconds: " opt
    cd ..
fi
echo "Capturing $opt seconds movie..."
gphoto2 --set-config movie=1 --wait-event=$(echo $opt)s --set-config movie=0 --wait-event-and-download=2s
