#!/bin/bash
lenght="$1"
if [ -z "$lenght" ]; then
    read -p "Lenght in seconds: " lenght
fi
echo "Capturing..."
gphoto2 --set-config movie=1 "--wait-event=${lenght}s" --set-config movie=0
echo "Downloading..."
sleep 1
$(dirname "$0")/get-last-photo
