#!/bin/bash
trap close INT

function close() {
    echo "Interrupted."
    exit 0
}

folder="$1"
if [ -z "$folder" ]; then
    read -e -p "Folder: " folder
fi
cd "$folder"
interval="$2"
if [ -z "$interval" ]; then
    read -p "Download interval: " interval
fi
echo "Press Ctrl-C to stop."
gphoto2 --get-all-files --keep --skip-existing
sleep 15
while true; do
	gphoto2 --get-all-files --keep --skip-existing
	sleep "$interval"
done
